basePath: /api/v1
definitions:
  api.AuthResponse:
    properties:
      errors:
        items:
          type: string
        type: array
      jweToken:
        type: string
    type: object
  api.IntegrationState:
    properties:
      connected:
        type: boolean
      error:
        type: string
      lastChecked:
        type: string
    type: object
  api.LoginSkippableResponse:
    properties:
      skippable:
        type: boolean
    type: object
  api.LoginSpec:
    properties:
      kubeconfig:
        type: string
      password:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
host: localhost:9090
info:
  contact: {}
  description: This is a Kubernetes-portal api server
  title: Kubernetes-portal API
  version: 0.0.1
paths:
  /integration/{name}/state:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.IntegrationState'
      summary: Return integration state
      tags:
      - integration
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Information required to authenticate user
        in: body
        name: LoginSpec
        required: true
        schema:
          $ref: '#/definitions/api.LoginSpec'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AuthResponse'
      summary: Return JWEToken
      tags:
      - Authentication
  /login/skippable:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.LoginSkippableResponse'
      summary: Return the authentication skip should be enabled or not
      tags:
      - Authentication
swagger: "2.0"
